### ISSUE TITLE
Missing some file changes

### ISSUE THREAD

**Issue by ADCJustinH** [Microsoft/vscode-filewatcher-windows#6]
I have a moderately nested folder structure (7 levels or so) when I use gulp to del / copy / replace files the file list in VS Code is not updated fully. I would guess that it is updating before the operation is complete and missing some of the files (which files it shows and which it does not appears random). I have to use windows explorer to reassure myself that the files are there...

VS Code 0.10.8

**Comment by bpasero** [comment]
@ADCJustinH you can run code with "--verbose" and open the developer console to see exactly what kind of file events are received, maybe you can review the changes when this happens?
